"""phase2m deal commission domain

Revision ID: 3baa98d42c55
Revises: 7350c4ab6e35
Create Date: 2026-08-31 10:56:11.092922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '3baa98d42c55'
down_revision: Union[str, Sequence[str], None] = '7350c4ab6e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('negotiation_room_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING_BUYER_APPROVAL', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='dealstatus'), nullable=False),
    sa.Column('buyer_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ownership_transfer_reference', sa.String(length=255), nullable=True),
    sa.Column('negotiation_evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['negotiation_room_id'], ['negotiation_rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negotiation_evidence_hash')
    )
    op.create_index(op.f('ix_deals_buyer_id'), 'deals', ['buyer_id'], unique=False)
    op.create_index('ix_deals_buyer_status', 'deals', ['buyer_id', 'status'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_listing_id'), 'deals', ['listing_id'], unique=False)
    op.create_index(op.f('ix_deals_merchant_id'), 'deals', ['merchant_id'], unique=False)
    op.create_index('ix_deals_merchant_status', 'deals', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_deals_negotiation_room_id'), 'deals', ['negotiation_room_id'], unique=False)
    op.create_index(op.f('ix_deals_offer_id'), 'deals', ['offer_id'], unique=True)
    op.create_index(op.f('ix_deals_request_id'), 'deals', ['request_id'], unique=False)
    op.create_index('ix_deals_request_status', 'deals', ['request_id', 'status'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('proposed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proposed_currency', sa.String(length=3), nullable=True),
    sa.Column('proposed_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('platform_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('platform_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('adjusted_by_platform', sa.Boolean(), nullable=False),
    sa.Column('merchant_accepted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'PAID', name='commissionstatus'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_deal_id'), 'commissions', ['deal_id'], unique=True)
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    op.create_index(op.f('ix_commissions_merchant_id'), 'commissions', ['merchant_id'], unique=False)
    op.create_index('ix_commissions_merchant_status', 'commissions', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index('ix_commissions_merchant_status', table_name='commissions')
    op.drop_index(op.f('ix_commissions_merchant_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_deal_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index('ix_deals_request_status', table_name='deals')
    op.drop_index(op.f('ix_deals_request_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_offer_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_negotiation_room_id'), table_name='deals')
    op.drop_index('ix_deals_merchant_status', table_name='deals')
    op.drop_index(op.f('ix_deals_merchant_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_listing_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index('ix_deals_buyer_status', table_name='deals')
    op.drop_index(op.f('ix_deals_buyer_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
