"""add deal delivery and receipt states

Revision ID: 93ec6a97adeb
Revises: 8c41f2a7b9d0
Create Date: 2026-09-04 15:24:08.025052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '93ec6a97adeb'
down_revision: Union[str, Sequence[str], None] = '8c41f2a7b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'received_at')
    op.drop_column('deals', 'delivered_at')
    # ### end Alembic commands ###
