"""add commission settings

Revision ID: a75902c7237c
Revises: d16f84
Create Date: 2026-09-05 09:55:28.401566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a75902c7237c'
down_revision: Union[str, Sequence[str], None] = 'd16f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_settings_id'), 'commission_settings', ['id'], unique=False)
    op.create_index('uq_commission_settings_active_currency', 'commission_settings', ['currency'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_commission_settings_active_currency', table_name='commission_settings', postgresql_where=sa.text('is_active IS true'))
    op.drop_index(op.f('ix_commission_settings_id'), table_name='commission_settings')
    op.drop_table('commission_settings')
    # ### end Alembic commands ###
