"""Add negotiation participant read state

Revision ID: b78a05f8e132
Revises: 43189b528483
Create Date: 2026-09-06 07:54:27.941080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'b78a05f8e132'
down_revision: Union[str, Sequence[str], None] = '43189b528483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiation_participants', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiation_participants', 'last_read_at')
    # ### end Alembic commands ###
